# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UIComponents' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
 pod 'RxSwift', '~> 5'
 pod 'RxCocoa', '~> 5'
 pod 'SnapKit', '~> 5'
 pod 'SDWebImage', '~> 5.0'
 pod 'PhoneNumberKit', '~> 2.6'

  # Pods for UIComponents

end
