//
//  VIPERHomeSceneViewController.swift
//  UIComponents
//
//  Created Лев Бондаренко on 28/06/2019.
//  Copyright © 2019 Лев Бондаренко. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class VIPERHomeSceneViewController: UIViewController, VIPERHomeSceneViewProtocol {

	var presenter: VIPERHomeScenePresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

}
