//
//  VIPERHomeSceneProtocols.swift
//  UIComponents
//
//  Created Лев Бондаренко on 28/06/2019.
//  Copyright © 2019 Лев Бондаренко. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol VIPERHomeSceneWireframeProtocol: class {

}
//MARK: Presenter -
protocol VIPERHomeScenePresenterProtocol: class {

}

//MARK: Interactor -
protocol VIPERHomeSceneInteractorProtocol: class {

  var presenter: VIPERHomeScenePresenterProtocol?  { get set }
}

//MARK: View -
protocol VIPERHomeSceneViewProtocol: class {

  var presenter: VIPERHomeScenePresenterProtocol?  { get set }
}
