//
//  VIPERHomeScenePresenter.swift
//  UIComponents
//
//  Created Лев Бондаренко on 28/06/2019.
//  Copyright © 2019 Лев Бондаренко. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class VIPERHomeScenePresenter: VIPERHomeScenePresenterProtocol {

    weak private var view: VIPERHomeSceneViewProtocol?
    var interactor: VIPERHomeSceneInteractorProtocol?
    private let router: VIPERHomeSceneWireframeProtocol

    init(interface: VIPERHomeSceneViewProtocol, interactor: VIPERHomeSceneInteractorProtocol?, router: VIPERHomeSceneWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
